data "aws_iam_policy_document" "lambda_assume_role" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "lambda_role" {
  name               = "${var.function_name}-role"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume_role.json
  tags               = var.tags
}

resource "aws_iam_role_policy_attachment" "lambda_basic_execution" {
  role       = aws_iam_role.lambda_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_secretsmanager_secret" "smartling_secret" {
  # checkov:skip=CKV_AWS_149: Using default KMS key for encryption is sufficient for this secret
  # checkov:skip=CKV2_AWS_57: Secret is static user credential, rotation not managed by this module
  name        = "${var.function_name}-smartling-secret"
  description = "Smartling User Secret for GTFS translation"
  tags        = var.tags
}

resource "aws_iam_role_policy" "lambda_permissions" {
  name = "GTFSTranslatorPermissions"
  role = aws_iam_role.lambda_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "secretsmanager:GetSecretValue"
        ]
        Effect   = "Allow"
        Resource = aws_secretsmanager_secret.smartling_secret.arn
      },
      {
        Action = [
          "s3:GetObject",
          "s3:PutObject"
        ]
        Effect = "Allow"
        Resource = [
          "arn:aws:s3:::${var.destination_bucket}/${var.destination_path}",
          "arn:aws:s3:::${var.destination_bucket}/${var.destination_path}*"
        ]
      }
    ]
  })
}

resource "aws_cloudwatch_log_group" "lambda_logs" {
  # checkov:skip=CKV_AWS_158: Log encryption with CMK not required for this task
  # checkov:skip=CKV_AWS_338: 14 days retention is sufficient and cost-effective for this project
  name              = "/aws/lambda/${var.function_name}"
  retention_in_days = 14
  tags              = var.tags
}

resource "aws_lambda_function" "translation_function" {
  # checkov:skip=CKV_AWS_117: Lambda does not require VPC as it only accesses public APIs and AWS services
  # checkov:skip=CKV_AWS_116: DLQ not required for this specific non-critical background task
  # checkov:skip=CKV_AWS_115: Concurrent execution limit handled by caller/triggering frequency
  # checkov:skip=CKV_AWS_272: Code signing not currently used in this pipeline
  # checkov:skip=CKV_AWS_173: Environment variables do not contain sensitive data (secrets are in Secrets Manager)
  # checkov:skip=CKV_AWS_50: X-Ray tracing not required for this simple translation task
  function_name = var.function_name
  role          = aws_iam_role.lambda_role.arn
  handler       = "gtfs_translation.lambda_handler.lambda_handler"
  runtime       = "python3.13"
  timeout       = var.lambda_timeout
  memory_size   = var.lambda_memory_size

  # The function.zip is generated by 'mise run build'
  filename = "${path.module}/../function.zip"
  source_code_hash = fileexists("${path.module}/../function.zip") ? filebase64sha256("${path.module}/../function.zip") : null

  environment {
    variables = {
      SMARTLING_USER_ID          = var.smartling_user_id
      SMARTLING_USER_SECRET_ARN  = aws_secretsmanager_secret.smartling_secret.arn
      SMARTLING_ACCOUNT_UID      = var.smartling_account_uid
      SOURCE_URL                 = var.source_url
      DESTINATION_BUCKET_URL     = "s3://${var.destination_bucket}/${var.destination_path}"
      TARGET_LANGUAGES           = join(",", var.target_languages)
    }
  }

  depends_on = [
    aws_cloudwatch_log_group.lambda_logs
  ]

  tags = var.tags
}
